### ISSUE TITLE
👍 middleware

### ISSUE THREAD

**Issue by TiceWise** [pravinnavale/Assignment1#1]
https://github.com/pravinnavale/Assignment1/blob/ae56afc1b3e6547a7b0db6b3c72ace2140f46793/apps/src/main.ts#L27

Nice to see that you used middleware!

**Comment by pravinnavale** [comment]
Is there a way to combine two app.use functions in single file?
Thanks,

**Comment by TiceWise** [comment]
Not sure what you mean; you can 'stack'/'chain' multiple app.use's, like you're already doing with bodyParser and this middleware.
