### ISSUE TITLE
minor readability

### ISSUE THREAD

**Issue by TiceWise** [pravinnavale/Assignment1#3]
https://github.com/pravinnavale/Assignment1/blob/ae56afc1b3e6547a7b0db6b3c72ace2140f46793/apps/src/main.ts#L49

would prefer `user.push(createUser(req, res, SimulatedDay));` for this line as it is more readable

**Comment by pravinnavale** [comment]
looks a good way, but I am used to assign array elements with index value, will it have any drawback?

**Comment by TiceWise** [comment]
No drawbacks, only advantages:
* Readability: user.push(...) is more readable and self-explanatory. Adopting more common practices like push can make the codebase more approachable for new team members and align with best practices in JavaScript/TypeScript development.
* Error Handling: When using array indices to assign values, you should be cautious about the index you are using. Assigning a value to an out-of-bounds index can lead to errors. The push method automatically appends to the end of the array, reducing the risk of such errors.
* Performance: In most cases, the performance difference between using an index and using push is negligible. Modern JavaScript engines are optimized to handle array operations efficiently.

If you want to insert at a specific index, you can use splice: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by pravinnavale** [comment]
Agree..
