### ISSUE TITLE
accessing headers

### ISSUE THREAD

**Issue by TiceWise** [pravinnavale/Assignment1#6]
https://github.com/pravinnavale/Assignment1/blob/ae56afc1b3e6547a7b0db6b3c72ace2140f46793/apps/src/getSimulatedDay.ts#L6

you don't need to iterate over all headers, you can access them directly with something like:
`req.headers.headerName`, but headerName in this case has a dash. You can access it like:
`req.headers['header-name']`

**Comment by pravinnavale** [comment]
done
